# Generated by Django 4.2.7 on 2023-12-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('fecha_publicacion', models.DateField(max_length=100)),
                ('isbn', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Nuevos_ingresos',
            },
        ),
    ]
