# Generated by Django 4.2.7 on 2023-12-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_libreria', '0002_alter_libro_precio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='libro',
            table='Nuevos_ingresos',
        ),
    ]
